// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://f2tue2hgcrhvxj7tvelfplchfq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-stm7uycxmzhcveaqdvxj4a4nci"
};

export default awsconfig;
